<?php
/**
 * @category  Extendware
 * @package   Extendware\FreeGift
 * @copyright 2020 Extendware
 */

/** @var $block \Extendware\FreeGift\Block\Cart\GiftRules */
$giftRules = $block->getGiftRules();
?>

<?php if ($giftRules) : ?>
    <?php
    /** @var \Extendware\FreeGift\Block\Cart\GiftRules\Rule $childBlock */
    $childBlock = $block->getChildBlock('checkout.cart.gift-rules.rule');
    ?>
    <div class="block free-gift" id="block-free-gift"
         data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
        <div class="title" data-role="title">
            <strong id="block-free-gift-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */
                __ ('Get free gift !') ?></strong>
        </div>
        <div class="content" data-role="content" aria-labelledby="block-free-gift-heading">
            <?php foreach ($giftRules as $rule) : ?>
                <?= $childBlock->setGiftRule($rule)->toHtml(); ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
