<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
$accountLink = '';
$signOutLink = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
    $accountLink = $block->getBaseUrl() . '/customer/account/';
    $signOutLink = $block->getBaseUrl() . '/customer/account/logout/';
}
?>
<li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <?php if (!$block->isLoggedIn()): ?>
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
        <?= /* @noEscape */ $dataPostParam ?>>
    <?php else: ?>
    <a>
    <?php endif; ?>
        <span><?= $escaper->escapeHtml(' My Account') ?></span>
    </a>
</li>

<script type="text/x-magento-init">
  {
     ".nav-toggle": {
         "mobileSearch": {}
     },
     ".header-right": {
         "myAccountPopup":{
             "isLoggedIn": "<?= $block->isLoggedIn() ?>",
             "accountLink": "<?= $accountLink ?>",
             "signOutLink": "<?= $signOutLink ?>"
         }
    }
  }
</script>

