<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
$accountLink = '';
$ordersLink = '';
$wishListLink = '';
$addressBookLink = '';
$accountInfoLink = '';
$paymentMethodsLink = '';
$billingLink = '';
$productReviewsLink = '';
$newsletterSubscrLink = '';
$signOutLink = '';

if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
    $accountLink = $block->getBaseUrl() . '/customer/account/';
    $ordersLink = $block->getBaseUrl() . 'sales/order/history/';
    $wishListLink = $block->getBaseUrl() . 'mwishlist/';
    $addressBookLink = $block->getBaseUrl() . 'customer/address/new/';
    $accountInfoLink = $block->getBaseUrl() . 'customer/account/edit/';
    $paymentMethodsLink = $block->getBaseUrl() . 'vault/cards/listaction/';
    $billingLink = $block->getBaseUrl() . 'paypal/billing_agreement/';
    $productReviewsLink = $block->getBaseUrl() . 'review/customer/';
    $newsletterSubscrLink = $block->getBaseUrl() . 'newsletter/manage/';
    $signOutLink = $block->getBaseUrl() . 'customer/account/logout/';

}
?>
<li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <?php if (!$block->isLoggedIn()): ?>
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
        <?= /* @noEscape */ $dataPostParam ?>>
    <?php else: ?>
    <a>
    <?php endif; ?>
        <span><?= $escaper->escapeHtml(' My Account') ?></span>
    </a>
</li>

<script type="text/x-magento-init">
  {
     ".nav-toggle": {
         "mobileSearch": {}
     },
     ".header-right": {
         "myAccountPopup":{
             "isLoggedIn": "<?= $block->isLoggedIn() ?>",
             "accountLink": "<?= $accountLink ?>",
             "ordersLink": "<?= $ordersLink ?>",
             "wishListLink": "<?= $wishListLink ?>",
             "addressBookLink": "<?= $addressBookLink ?>",
             "accountInfoLink": "<?= $accountInfoLink ?>",
             "paymentMethodsLink": "<?= $paymentMethodsLink ?>",
             "billingLink": "<?= $billingLink ?>",
             "productReviewsLink": "<?= $productReviewsLink ?>",
             "newsletterSubscrLink": "<?= $newsletterSubscrLink ?>",
             "signOutLink": "<?= $signOutLink ?>"
         }
    }
  }
</script>

