<?php
/**
 * Blog post info template
 *
 * @var $block \Magefan\Blog\Block\Post\Info
 */
?>

<?php $_post = $block->getPost() ?>

<div class="post-info">
    <?php if ($block->authorEnabled()) { ?>
        <?php if ($_author = $_post->getAuthor()) { ?>
            <div class="item post-author">
                <span class="label"><?= $block->escapeHtml(__('Posted by')) ?></span>
                <span class="value">
                <?php if ($authorPageEnabled = $block->authorPageEnabled()) { ?>
                <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                   href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>">
                <?php } ?>
                <span class="post-header">
                <?= $block->escapeHtml($_author->getTitle()) ?>
                </span>

                <?php if ($authorPageEnabled) { ?>
                </a>
                <?php } ?>
            </span>
            </div>
        <?php } ?>
    <?php } ?>
    <?php if ($_post->isPublishDateEnabled()) { ?>
        <div class="item post-posed-date">
            <span class="label"><?= $block->escapeHtml(__('on')) ?></span>
            <span class="value"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
        </div>
    <?php } ?>
</div>
