<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Multiple Wishlist for Magento 2
*/
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div data-amwishlist-js="tabs-block">
    <?= $block->getChildHtml('tabs') ?>
</div>
<div data-amwishlist-js="content-tabs-block">
    <?= $block->getChildHtml('list') ?>
    <?= $block->getChildHtml('new') ?>
</div>
