<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>


<?php if ($block->canShowBlock()) : ?>
    <?php $activeFilters = $block->getActiveFilters(); ?>
    <div class="filter-toggler"><?= $block->escapeHtml(__('Filter'))?></div>
    <div class="block filter start" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @escapeNotVerified */
        $filtered ?>">
            <div data-role="title">
                <span class="refine-by-block"><?= $block->escapeHtml(__('Refine by'))?></span>
                <span class="show-hide-toggle"><?= $block->escapeHtml(__('Show Filters'))?></span>
            </div>
        </div>

        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */
                    echo $block->getClearUrl() ?>"
                       class="action clear filter-clear"><span><?php /* @escapeNotVerified */
                            echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
        <?php if ($filter->getItemsCount()) : ?>
        <?php if (!$wrapOptions) : ?>

            <div class="filter-options" id="narrow-by-list" data-role="content"
                 data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": <?php /* @noEscape */
                 echo $activeFilters; ?>, "multipleCollapsible": true}}'>
                <?php $wrapOptions = true; ?>
                <?php endif; ?>
                <div data-role="collapsible" class="filter-options-item">
                    <div data-role="title" class="filter-options-title"><?= /* @escapeNotVerified */
                        __($filter->getName()) ?></div>
                    <div data-role="content" class="filter-options-content"><?= /* @escapeNotVerified */
                        $block->getChildBlock('renderer')->render($filter) ?></div>
                </div>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions) : ?>
            </div>
        <?php else : ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
            <?php endif; ?>
        </div>
    </div>
    <div class="widget block block-sort-by">
        <?=  $block->getChildHtml('toolbar_toggle');?>
    </div>

<?php endif; ?>
