<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <span class="footer-content">
         <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
         <div class="footer-payment-icons">
             <span class="visa"></span>
             <span class="american-express"></span>
             <span class="discovery"></span>
             <span class="mastercard"></span>
             <span class="paypal"></span>
         </div>
    </span>
</small>
<script type="text/x-magento-init">
{
    ".page-header":{
        "headerFixed":{
        }
    }
}
</script>
