<?php
use Magento\Framework\App\Action\Action;
use Magento\Catalog\Helper\Data;
use Magento\Catalog\Helper\Image;
use Magento\Framework\App\ObjectManager;
// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 *  * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = ObjectManager::getInstance();
/** WeltPixel_GoogleTagManager  */
$gtmHelper = $this->helper('WeltPixel\GoogleTagManager\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $showCart = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $showCart = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned() ?? '';
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image?>
                    <div class="product-item-photo">
                        <?php
                        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                        $images = $product->getMediaGalleryImages();
                        $i = 1;
                        ?>
                        <?php if (!empty($images)) { ?>
                            <?php foreach ($images as $child) { ?>
                                <?php if ($i < 3): ?>
                                    <a class="img-<?= $i++ ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>">
                                        <img src="<?php echo $child->getUrl(); ?>" alt="none"/>
                                    </a>
                                <?php endif; ?>
                            <?php } ?>
                        <?php } else { ?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
                               class="product-item-photo">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                        <?php } ?>
                        <?php if ($showCart): ?>
                            <?php if ($_product->isSaleable()): ?>
                                <div class="button-container">
                                    <div class="actions-primary">
                                        <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                            <button class="action tocart primary"
                                                    data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_product)) ?>"}}'
                                                    type="button"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <?php
                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                                                ?>
                                                <button class="action tocart primary"
                                                        data-post='<?= /* @noEscape */
                                                        $postData ?>' type="button"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            <?php else: ?>
                                                <div class="stock unavailable">
                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php else: ?>
                                <div class="button-container-unavailable">
                                    <button><span><?= $block->escapeHtml(__('Out of stock')) ?></span></button>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?= /* @noEscape */
                                $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= /* @noEscape */
                        $block->getProductPrice($_product) ?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>


                        <?= $block->getProductDetailsHtml($_product) ?>

                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                 "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
