<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Multiple Wishlist for Magento 2
*/
?>
<?php
/** @var \Amasty\MWishlist\Block\Account\Wishlist\Wishlist $block */
?>

<?php if ($block->getHelperContext()->getWishlistHelper()->isAllow()): ?>
    <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    <form class="form-wishlist-items" id="wishlist-view-form"
          data-amwishlist-js="wishlist-form"
          data-mage-init='{"wishlist":{
          "addToCartUrl":<?= /* @noEscape */ $block->getItemAddToCartParams("%item%") ?>,
          "addAllToCartUrl":<?= /* @noEscape */ $block->getAddAllToCartParams() ?>,
          "commentString":""},
          "validation": {}}' action="<?= $block->escapeUrl($block->getUpdateUrl()) ?>" method="post">
        <?= $block->getChildHtml('customer.mwishlist.title'); ?>

        <div data-amwishlist-js="items-block">
            <?php if ($block->hasWishlistItems()): ?>
                <?= $block->getBlockHtml('formkey') ?>
                <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
                <?= $block->getChildHtml('items') ?>
            <?php else: ?>
                <div class="message info empty"><span><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></span></div>
            <?php endif ?>

            <?php if ($block->hasWishlistItems() && $block->getWishlistItemsCount() > 1) :?>
                <button type="button" data-role="all-tocart" title="<?= $block->escapeHtmlAttr(__('Add All to Cart')) ?>" class="action tocart">
                    <span><?= $block->escapeHtml(__('Add All to Cart')) ?></span>
                </button>
            <?php endif;?>
        </div>
    </form>
<?php endif ?>
