<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Form $block */
//phpcs:disable Generic.Files.LineLength
$product = $block->getProduct();

?>
<div class="block review-add">
    <div class="background-review"></div>
    <div class="block-title"><strong><?= $block->escapeHtml(__('Write Your Own Review')) ?></strong></div>
    <div class="button-review-popup">
        <button><?= $block->escapeHtml(__('Write a Review')) ?></button>
    </div>
    <div class="block-content">
        <?php if ($block->getAllowWriteReviewFlag()):?>
            <div class="title-review">
                <p><?= $block->escapeHtml(__('Write a Review')) ?></p>
                <div class="close-button-review">
                    <span>×</span>
                </div>
            </div>
            <div class="review-block-content">
                <div class="review-add-img">
                    <?php
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($block->getProductInfo()->getId());
                    $images = $product->getMediaGalleryImages();
                    $i = 1;
                    ?>
                    <?php if (!empty($images)) { ?>
                        <?php foreach ($images as $child) { ?>
                            <?php if ($i < 2): ?>
                                <a class="img-<?= $i++ ?>"
                                   href="<?= $block->escapeUrl($block->getProductUrl($block->getProductInfo()->getId())) ?>">
                                    <img src="<?php echo $child->getUrl(); ?>" alt="none"/>
                                </a>
                            <?php endif; ?>
                        <?php } ?>
                    <?php } else { ?>
                        <a href="<?= $block->escapeHtml($block->getProductInfo()->getProductUrl()) ?>">
                            <img src="<?= $block->getBaseUrl()?>media/catalog/product/cache/<?= $block->getProductInfo()->getImage()?>" alt="none"/>
                        </a>
                    <?php } ?>
                    <div class="name">
                        <p><?= $block->escapeHtml(__($block->getProductInfo()->getName())) ?></p>
                    </div>
                </div>
                <form action="<?= $block->escapeUrl($block->getAction()) ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
                    <?= $block->getBlockHtml('formkey') ?>
                    <?= $block->getChildHtml('form_fields_before') ?>
                    <fieldset class="fieldset review-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                            <span id="input-message-box"></span>
                            <fieldset class="field required review-field-ratings">
                                <legend class="label"><span><?= $block->escapeHtml(__('Rating')) ?></span></legend>
                                <div class="control">
                                    <div class="nested" id="product-review-table">
                                        <?php foreach ($block->getRatings() as $_rating): ?>
                                            <div class="field choice review-field-rating">
                                                <label class="label" id="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?= $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                                                <div class="control review-control-vote">
                                                    <?php $options = $_rating->getOptions();?>
                                                    <?php $iterator = 1; foreach ($options as $_option): ?>
                                                        <input
                                                            type="radio"
                                                            name="ratings[<?= $block->escapeHtmlAttr($_rating->getId()) ?>]"
                                                            id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                                            value="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                                                            class="radio"
                                                            data-validate="{'rating-required':true}"
                                                            aria-labelledby="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label <?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label" />
                                                        <label
                                                            class="rating-<?= $block->escapeHtmlAttr($iterator) ?>"
                                                            for="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                                            title="<?= $block->escapeHtmlAttr(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>"
                                                            id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label">
                                                            <span><?= $block->escapeHtml(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?></span>
                                                        </label>
                                                        <?php $iterator++; ?>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                    <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                                </div>
                            </fieldset>
                        <?php endif ?>
                        <div class="field review-field-nickname required">
                            <label for="nickname_field" class="label"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                            <div class="control">
                                <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
                            </div>
                        </div>
                        <div class="field review-field-email required">
                            <label for="email_field" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" type="email" id="email_field"
                                       data-mage-init='{"mage/trim-input":{}}'
                                       data-validate="{required:true, 'validate-email':true}"
                                />
                            </div>
                        </div>
                        <div class="field review-field-summary required">
                            <label for="summary_field" class="label"><span><?= $block->escapeHtml(__('Review Subject')) ?></span></label>
                            <div class="control">
                                <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
                            </div>
                        </div>
                        <div class="field review-field-text required">
                            <label for="review_field" class="label"><span><?= $block->escapeHtml(__('Comments')) ?></span></label>
                            <div class="control">
                                <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                            </div>
                        </div>
                    </fieldset>
                    <div class="actions-toolbar review-form-actions">
                        <div class="primary actions-primary">
                            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit Review')) ?></span></button>
                        </div>
                    </div>
                </form>
            </div>
            <script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {},
        "Magento_Review/js/validate-review": {},
        "Magento_Review/js/submit-review": {}
    }
}
</script>
        <?php else: ?>
            <div class="message info notlogged" id="review-form">
                <div>
                    <?= $block->escapeHtml(__('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
