<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 *  * @var \Magento\Framework\Escaper $escaper
 */
?>
<script type="text/x-magento-init">
            {
                ".banner-content-mobile.owl-carousel": {
                    "owlCarousel": {
                        "center": false,
                        "margin": 0,
                        "items": 1,
                        "loop": true,
                        "autoplay": true,
                        "autoplayTimeout": 3000,
                        "autoplayHoverPause": true,
                        "nav": false,
                        "dots": false,
                        "responsiveClass": true,
                        "responsive": {
                            "0": {
                                "items": 1
                            }
                        }
                    }
                }
            }
</script>
