<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int)$block->isShuffled();
            $isWeightedRandom = (int)$block->getRotation()->isWeightedRandom($block->getProductListType());
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $isWeightedRandom = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int)$block->isShuffled();
            $isWeightedRandom = (int)$block->getRotation()->isWeightedRandom($block->getProductListType());

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $isWeightedRandom = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
$_item = null;
?>

<?php if ($exist): ?>

<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>"
     data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
     data-shuffle="<?= /* @noEscape */
     $shuffle ?>"
     data-shuffle-weighted="<?= /* @noEscape */
     $isWeightedRandom ?>">
    <?php else: ?>
    <div class="block <?= $block->escapeHtmlAttr($class) ?>"
         data-mage-init='{"upsellProducts":{}}'
         data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
         data-shuffle="<?= /* @noEscape */
         $shuffle ?>"
         data-shuffle-weighted="<?= /* @noEscape */
         $isWeightedRandom ?>">
        <?php endif; ?>
        <?php else: ?>
        <div class="block <?= $block->escapeHtmlAttr($class) ?>">
            <?php endif; ?>
            <div class="block-title title">
                <strong id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading"
                        aria-level="2"><?= $block->escapeHtml($title) ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                    <ol class="products list items product-items related owl-carousel">
                        <?php foreach ($items as $_item): ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell'): ?>
                                <li class="item product product-item"
                                id="product-item_<?= /* @noEscape */
                                $_item->getId() ?>"
                                data-shuffle-group="<?= $block->escapeHtmlAttr($_item->getPriority()) ?>" >
                                <?= /* @noEscape */
                                $secureRenderer->renderStyleAsTag(
                                    'display:none;',
                                    'li#product-item_' . $_item->getId()
                                ) ?>
                            <?php else: ?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info <?= /* @noEscape */
                            $available ?>">
                                <?= /* @noEscape */
                                '<!-- ' . $image . '-->' ?>
                                <?php // Product Image ?>
                                <div class="product-item-photo">
                                    <?php
                                    $_helperGallery = $this->helper('IdeaInYou\GalleryImages\Helper\Data');
                                    $_helperGallery->addGallery($_item);
                                    $images = $_helperGallery->getGalleryImages($_item);
                                    $i = 1;
                                    ?>
                                    <?php if (!empty($images)) { ?>
                                        <?php foreach ($images as $child) { ?>
                                            <?php if ($i < 3): ?>
                                                <a class="img-<?= $i++ ?>"
                                                   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                                    <img src="<?php echo $child->getUrl(); ?>" alt="none"/>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>
                                    <?php } else { ?>
                                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                           class="product-item-photo">
                                            <?= $block->getImage($_item, $image)->toHtml() ?>
                                        </a>
                                    <?php } ?>
                                    <?php if (!($_item->isSaleable())): ?>
                                        <div class="button-container-unavailable">
                                            <button><span><?= $block->escapeHtml(__('Out of stock')) ?></span></button>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($_item->isSaleable()): ?>
                                    <div class="button-container">
                                        <div class="actions-primary">
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary"
                                                            data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                            type="button"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?= /* @noEscape */
                                                                $postData ?>' type="button"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <div class="button-container-unavailable">
                                                            <button><span><?= $block->escapeHtml(__('Out of stock')) ?></span></button>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                <div class="product details product-item-details">
                                    <h4 class="product name product-item-name"><a
                                            class="product-item-link"
                                            title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                            href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </h4>

                                    <?= /* @noEscape */
                                    $block->getProductPrice($_item) ?>

                                    <!-- Reviews Stars -->
                                    <div class="product-list-rating-stars">
                                        <?php echo $block->getReviewsSummaryHtml($_item, false, true); ?>
                                    </div>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
        <?php if (!$block->isRedirectToCartEnabled() && $_item): ?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                    }
                }
            }

            </script>
        <?php endif; ?>
        <?php endif; ?>
        <script type="text/x-magento-init">
            {
                ".related.owl-carousel": {
                    "owlCarousel": {
                        "center": false,
                        "items": 4,
                        "margin":16,
                        "loop": false,
                        "nav": true,
                        "dots": false,
                        "responsiveClass": true,
                        "navText": ["<div class='nav-btn prev-slide'></div>","<div class='nav-btn next-slide'></div>"],
                        "responsive": {
                            "0": {
                                "items": 2,
                                "margin":16
                            },
                            "360": {
                                "items": 2,
                                "margin":16
                            },
                             "768": {
                                "items": 3,
                                "margin":30
                            },
                             "880": {
                                "items": 4,
                                "margin":30
                            }
                        }
                    }
                }
            }

        </script>
