<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Review\Block\Product\ReviewRenderer $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<?php if ($block->isReviewEnabled() && $block->getReviewsCount()) : ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
        <div class="rating-start">
        <?php if ($rating) :?>
        <div class="rating-summary">
             <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
             <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating); ?>%">
                 <span style="width:<?= $block->escapeHtmlAttr($rating); ?>%">
                     <span>
                         <span itemprop="ratingValue"><?= $block->escapeHtml($rating); ?></span>% of <span itemprop="bestRating">100</span>
                     </span>
                 </span>
             </div>
         </div>
        <?php else: ?>
            <div class="rating-empty">
                <span class="icon-rating-empty"></span>
            </div>
        <?php endif;?>
        <div class="reviews-actions">
            <div class="rating-result">
            <a class="action view"
               href="<?= $block->escapeUrl($url) ?>">
                <span>(<?= $block->escapeHtml($block->getReviewsCount()) ?> <?= ($block->getReviewsCount() == 1) ? $block->escapeHtml(__('review')) : $block->escapeHtml(__('reviews')) ?>)</span>
            </a>
            </div>
        </div>
        </div>
        <div class="rating-write">
            <a class="action add"><?= $block->escapeHtml(__('Write a Review')) ?></a>
        </div>
    </div>
<?php elseif ($block->isReviewEnabled() && $block->getDisplayIfEmpty()) : ?>
    <div class="product-reviews-summary empty">
        <div class="reviews-actions">
            <div class="rating-result">
                <div class="rating-empty">
                    <span class="icon-rating-empty"></span>
                </div>
                <div class="text-empty">
                    <p>(<?= $block->escapeHtml(__('No reviews yet')) ?>)</p>
                </div>
            </div>
            <div class="rating-write">
            <a class="action add">
                <?= $block->escapeHtml(__('Write a Review')) ?>
            </a>
            </div>
        </div>
    </div>
<?php endif; ?>
